### DISCUSSION TITLE
Как получить доступ к картинке с погодой?

### DISCUSSION THREAD

**Discussion by CRASH-Tech** [IATkachenko/HA-YandexWeather#32] [Q&A]
### В чем проблема?

subj

### При использовании какой версии интеграции возникает проблема?

latest

### Какая версия Home Assistant используется?

latest

### Какой способ установки Home Assistant используется?

Home Assistant OS

**Comment by IATkachenko** [comment]
Как написано в reame, cсылка на картинку с погодным состоянием находится в атрибуте `entitiy_picture`, объекта `weather.yandex_weather`
![изображение](https://user-images.githubusercontent.com/17473830/169655346-732b1554-dd01-47ce-b660-6ae9d8f7b7a7.png)

В `floorplan-card` можно использовать так:
```yaml
config:
  rules:
    - entity: weather.yandex_weather
      image_template: ${entity.attributes.entity_picture}
```

ps. более аккуратное формулирвоание вопросов, обычно, позволяет получать более полезные и качественные ответы.
pps. перенес в Q&A
