### DISCUSSION TITLE
датчики недоступны

### DISCUSSION THREAD

**Discussion by mayhemuss** [IATkachenko/HA-YandexWeather#55] [Q&A] [answered]
напротив почти всех параметров стоит неизвестно
![image](https://user-images.githubusercontent.com/104756484/196968224-09232f58-23ee-44f0-ac4e-7c4dd9325d1c.png)
![image](https://user-images.githubusercontent.com/104756484/196968331-93d3ae45-4fb0-4329-ae5d-1e1f7883f9a5.png)

**Comment by IATkachenko** [comment]
Доброго дня.

А в логах что при этом? Желательно на `debug`  уровне.

в configuration.yaml нужно прописать
```yaml
logger:
  default: warning
  logs:
    custom_components.yandex_weather: debug
```
и перезапустить HA
