### ISSUE TITLE
Добавить сенсор с давлением в мм рт. ст.

### ISSUE THREAD

**Issue by IATkachenko** [IATkachenko/HA-YandexWeather#11]
> Не корректно отражается давление в атрибутах, в сенсоре всё корректно и хотелось бы возможность его выводить в мм рт. ст.

С давлением в мм рт. ст. Очень давняя тема. Лучше не ждать, а добавить сенсор/конвертер.
```   
 pressure_mmhg_weather:
      friendly_name: "Давление"
      unit_of_measurement: 'mmHg'
      value_template: "{{ (states('sensor.yandex_weather_pressure')|float(default=0) * 0.7500637)|round(0) }}"
      icon_template: mdi:gauge
```

_Originally posted by @alexls74 in https://github.com/IATkachenko/HA-YandexWeather/issues/8#issuecomment-1030490533_
