### ISSUE TITLE
Temperatrue вместо temperature

### ISSUE THREAD

**Issue by lunguch** [IATkachenko/HA-YandexWeather#116]
### В чем проблема?

Temperatrue вместо temperature  в weather.yandex_weather.
```
forecast:
  - datetime: "2024-04-09T06:00:00+03:00"
    wind_bearing: 0
    native_temperature: 7
    temperatrue: 7
    native_templow: 7
    templow: 7
    native_pressure: 1011
    native_wind_speed: 0
    condition: cloudy
  - datetime: "2024-04-09T13:26:16.362045+03:00"
    wind_bearing: 45
    native_temperature: 14
    temperature: 14
    native_templow: 12
    templow: 12
    native_pressure: 1013
    native_wind_speed: 1.9
    native_precipitation: 0
    precipitation_probability: 0
    condition: cloudy
    is_daytime: true
  - datetime: "2024-04-09T19:26:16.362045+03:00"
    wind_bearing: 90
    native_temperature: 12
    temperature: 12
    native_templow: 10
    templow: 10
    native_pressure: 1014
    native_wind_speed: 1.2
    native_precipitation: 0
    precipitation_probability: 0
    condition: cloudy
    is_daytime: true
```

### При использовании какой версии интеграции возникает проблема?

3.2.1

### Какая версия Home Assistant используется?

2024.4.2

### Какой способ установки Home Assistant используется?

Home Assistant OS

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом
