### ISSUE TITLE
Вероятность осадков на сегодня

### ISSUE THREAD

**Issue by xomarnd** [IATkachenko/HA-YandexWeather#119]
### В чем проблема?

В данных получаемых HA есть вероятность осадков на завтра и послезавтра, но нет на сегодня. 

Вот данные из панели разработчика:
```
temperature: 16
temperature_unit: °C
humidity: 41
pressure: 751.56
pressure_unit: mmHg
wind_bearing: 225
wind_speed: 7.2
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
feels_like: 13
wind_gust: 5.8
yandex_condition: Облачно с прояснениями
forecast_icons: bkn_-ra_n, bkn_d
forecast: 
- datetime: '2024-04-30T21:00:00+03:00'
  wind_bearing: 225
  native_temperature: 16
  temperature: 16
  native_templow: 16
  templow: 16
  native_pressure: 1002
  native_wind_speed: 2
  condition: cloudy
  is_daytime: false
- datetime: '2024-05-01T03:52:03.831955+03:00'
  wind_bearing: 270
  native_temperature: 14
  temperature: 14
  native_templow: 12
  templow: 12
  native_pressure: 1002
  native_wind_speed: 2.1
  native_precipitation: 0.7
  precipitation_probability: 20
  condition: rainy
  is_daytime: false
- datetime: '2024-05-01T09:52:03.831955+03:00'
  wind_bearing: 315
  native_temperature: 14
  temperature: 14
  native_templow: 12
  templow: 12
  native_pressure: 1002
  native_wind_speed: 3.1
  native_precipitation: 0
  precipitation_probability: 10
  condition: cloudy
  is_daytime: true

temp_water: null
attribution: Data provided by Yandex Weather
entity_picture: https://yastatic.net/weather/i/icons/funky/dark/bkn_n.svg
friendly_name: Yandex Weather
supported_features: 4
```
### При использовании какой версии интеграции возникает проблема?

3.2.5

### Какая версия Home Assistant используется?

2024.4.4

### Какой способ установки Home Assistant используется?

Home Assistant Container

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом
