### ISSUE TITLE
Ошибка SSL и ограничение работы интеграции в определенное время

### ISSUE THREAD

**Issue by artek79** [IATkachenko/HA-YandexWeather#145]
Спасибо за интеграцию!

Стала вылезать ошибка:

Source: custom_components/yandex_weather/updater.py:258
integration: Yandex Weather (documentation, issues)
First occurred: 13:00:00 (1 occurrences)
Last logged: 13:00:00
/usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning warnings.warn(

"фикс" в updater.py не помогает(

```
transport = AIOHTTPTransport(
    url=API_URL, headers={"X-Yandex-Weather-Key": self.__api_key}, timeout=20, ssl=False
)
```

И еще, есть необходимость отключать интеграцию (например ночью) что бы не тратились запросы тк их мало... мб добавить такую опцию в конфиг? пока сделал так:

```
alias: Yandex Weather Off
trigger: time
at: "03:01:00"
id: yandex-weather-off

alias: Yandex Weather On
trigger: time
at: "09:00:00"
id: yandex-weather-on

choose:
  - conditions:
      - condition: trigger
        id:
          - yandex-weather-off
    sequence:
      - action: homeassistant.disable_config_entry
        metadata: {}
        data:
          config_entry_id: 547907b2ea6cadfc0b280234a86e1cc4
  - conditions:
      - condition: trigger
        id:
          - yandex-weather-on
    sequence:
      - action: homeassistant.enable_config_entry
        metadata: {}
        data:
          config_entry_id: 547907b2ea6cadfc0b280234a86e1cc4
alias: Yandex Weather ON/OFF
```

в настройках стоит 24 запроса в сутки и при таком раскладе получается 16 запросов (когда интеграция включена) и четко укладываемся в лимит 500 в месяц.
