### ISSUE TITLE
Duplicate lines in the forecast

### ISSUE THREAD

**Issue by m-larin** [IATkachenko/HA-YandexWeather#63]
### В чем проблема?

When displaying the forecast, the days of the week are duplicated. At the same time, the temperature varies.

![image](https://user-images.githubusercontent.com/38663339/207530799-d8cfe743-e2df-453c-b3ac-33941432cf29.png)

Perhaps you need to add the time to the line.
### При использовании какой версии интеграции возникает проблема?

`2.0.0`

### Какая версия Home Assistant используется?

`2022.12.5`

### Какой способ установки Home Assistant используется?

`Home Assistant Supervised`

**Comment by IATkachenko** [comment]
It is not duplicate.
Yandex is providing forecast data for next two times of day: if you check weather in the morning it will be "day" and "evening".
and the integration translates it to timestamps _(with datetime)_, but UI card is not show full datetime.

So, on the screenshot you may see forecasts for today "day" and "evening" and the integration can not affect to a way that UI show data.

In states (developer tools of Home Assistant) it looks like:
```
forecast: 
- datetime: '2022-12-14T14:56:27.543932'
  wind_bearing: 270
  condition: snowy
  precipitation_probability: 90
  temperature: -4
  templow: -4
  pressure: 739.56
  wind_speed: 5.7
  precipitation: 0.8
- datetime: '2022-12-14T20:56:27.543932'
  wind_bearing: 270
  condition: snowy
  precipitation_probability: 40
  temperature: -4
  templow: -5
  pressure: 744.81
  wind_speed: 4.8
  precipitation: 0.4
```
