### ISSUE TITLE
Не корректно отражается давление в атрибутах

### ISSUE THREAD

**Issue by BertTomsk** [IATkachenko/HA-YandexWeather#8]
Добрый день!
Не корректно отражается давление в атрибутах, в сенсоре всё корректно и хотелось бы возможность его выводить в мм рт. ст.
![S20203-21310646](https://user-images.githubusercontent.com/62449149/152407146-07d1c44d-8eff-44c3-b1ba-1c2718ba4e65.jpg)
![S20203-21314050](https://user-images.githubusercontent.com/62449149/152407273-e9090a48-4f00-49f9-be9c-e6c55786476e.jpg)
И возможно добавить прогноз как в гисметео?
Сверху яндекс, снизу гисметео
![S20203-21383794](https://user-images.githubusercontent.com/62449149/152407499-f59de924-903c-4fee-919d-5e3df51e11fd.jpg)

**Comment by IATkachenko** [comment]
С отображением давления -- это в Home Assistant core идти надо.
Проблем есть целых три:
1. мм рт. столба, по мнению Home Assistant не является единицей давления
2. единицы при отображении приводятся к системным, а системная единица давления -- Паскаль. Даже не гекто-паскаль
3. UI рисует что ему взбредет в голову и не ориентируется на то что HA отдал давление в системных единицах.

И в районе HomeAssistnat core про это есть очень интересные дискуссии :)

Так что сделать что-то нельзя. Но за ситуацией я слежу и как-только будет возможноть что-то сделать -- обязательно сделаю.

ps. Если вы откроете погодную карточку, как на первом скрине, для gismeteo, то увидите что на ней давление 1000 Pa, что немного маловато ;)

**Comment by IATkachenko** [comment]
Прогно -- будет в ближайшее время. Не все сразу :) Но Яндекс отдает прогно на 2 интервала (условно день и вечер), так что почасового или на неделю из него добыть нельзя. По крайней мере на бесплатном тарифе.

**Comment by IATkachenko** [comment]
И да, обратите внимание еще на скорость ветра, когда она больше нуля будет. Там тоже такой же бардак.

**Comment by alexls74** [comment]
> Не корректно отражается давление в атрибутах, в сенсоре всё корректно и хотелось бы возможность его выводить в мм рт. ст.

С давлением в мм рт. ст. Очень давняя тема. Лучше не ждать, а добавить сенсор/конвертер.
```   
 pressure_mmhg_weather:
      friendly_name: "Давление"
      unit_of_measurement: 'mmHg'
      value_template: "{{ (states('sensor.yandex_weather_pressure')|float(default=0) * 0.7500637)|round(0) }}"
      icon_template: mdi:gauge
```
