### ISSUE TITLE
Не изменяется обозначение единицы измерения температуры на Цельсии

### ISSUE THREAD

**Issue by thedemoncat** [IATkachenko/HA-YandexWeather#96]
### В чем проблема?

При изменении  в настройках отображения температуры с Фаренгейт нв Цельсии, значение пересчитывается, но единица измерения остается так же F

```
lovelace:
  mode: yaml
  resources:
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module
```

```
  - title: Main
    icon: 'mdi:home-circle'
    cards:
      - type: custom:weather-card
        entity: weather.yandex_weather
        sun: sun.sun
        name: Погода
        current: true
        details: true
        forecast: true
        hourly_forecast: true
        number_of_forecasts: 5.
```

![Screenshot 2024-01-13 082432](https://github.com/IATkachenko/HA-YandexWeather/assets/26283990/b493f91d-b25c-4bfe-a580-7489640dc07b)

### При использовании какой версии интеграции возникает проблема?

v3,1,2

### Какая версия Home Assistant используется?

2024.1.3

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом
